Try constraining the type of an object with a return type
```
src/html-pages/save-article-form-page/construct-view-model.ts:30:5 - error TS2322: Type '{ propertyThatIsNotInTheViewModelType: number; article: { name: SanitisedHtmlFragment; id: ArticleId; }; userLists: readonly { id: ListId; name: string; description: string; articleIds: string[]; updatedAt: Date; ownerId: { ...; } | { ...; }; }[]; pageHeading: Branded<...>; }' is not assignable to type 'ViewModel'.
  Object literal may only specify known properties, and 'propertyThatIsNotInTheViewModelType' does not exist in type 'ViewModel'.

30     propertyThatIsNotInTheViewModelType: 42,
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[09:10:49] Found 1 error. Watching for file changes.
```