Attempt reuse naively #3531
```
src/read-side/non-html-views/api/groups/groups.ts:9:3 - error TS2345: Argument of type 'ViewModel' is not assignable to parameter of type 'StatusData'.
  Type 'readonly GroupStatus[]' is not assignable to type 'readonly StatusData[]'.
    Type 'GroupStatus' is not assignable to type 'StatusData'.
      Type 'GroupStatus' is not assignable to type 'StatusDataRecord'.
        Property 'largeLogoPath' is incompatible with index signature.
          Type 'Option<string>' is not assignable to type 'StatusData'.
            Type 'None' is not assignable to type 'StatusData'.
              Type 'None' is not assignable to type 'StatusDataRecord'.
                Index signature for type 'string' is missing in type 'None'.
```