Add a property to the view model
Produces 2 errors:
```
src/html-pages/save-article-form-page/construct-view-model.ts:15:85 - error TS2322: Type 'TaskEither<DataError, { article: { name: SanitisedHtmlFragment; id: ArticleId; }; userLists: readonly { id: ListId; name: string; description: string; articleIds: string[]; updatedAt: Date; ownerId: { ...; } | { ...; }; }[]; pageHeading: Branded<...>; }>' is not assignable to type 'TaskEither<DataError, ViewModel>'.
  Property 'newPropertyWeWantToAdd' is missing in type '{ article: { name: SanitisedHtmlFragment; id: ArticleId; }; userLists: readonly { id: ListId; name: string; description: string; articleIds: string[]; updatedAt: Date; ownerId: { ...; } | { ...; }; }[]; pageHeading: Branded<...>; }' but required in type 'ViewModel'.

 15 export const constructViewModel: ConstructViewModel = (dependencies) => (params) => pipe(
                                                                                        ~~~~~
 16   {
    ~~~
...
 37   } satisfies ViewModel)),
    ~~~~~~~~~~~~~~~~~~~~~~~~~~
 38 );
    ~

  src/html-pages/save-article-form-page/view-model.ts:15:3
    15   newPropertyWeWantToAdd: string,
         ~~~~~~~~~~~~~~~~~~~~~~
    'newPropertyWeWantToAdd' is declared here.
  src/html-pages/save-article-form-page/construct-view-model.ts:13:59
    13 type ConstructViewModel = (dependencies: Dependencies) => (params: Params) => TE.TaskEither<DE.DataError, ViewModel>;
                                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    The expected type comes from the return type of this signature.

src/html-pages/save-article-form-page/construct-view-model.ts:37:5 - error TS1360: Type '{ article: { name: SanitisedHtmlFragment; id: ArticleId; }; userLists: readonly { id: ListId; name: string; description: string; articleIds: string[]; updatedAt: Date; ownerId: { ...; } | { ...; }; }[]; pageHeading: Branded<...>; }' does not satisfy the expected type 'ViewModel'.
  Property 'newPropertyWeWantToAdd' is missing in type '{ article: { name: SanitisedHtmlFragment; id: ArticleId; }; userLists: readonly { id: ListId; name: string; description: string; articleIds: string[]; updatedAt: Date; ownerId: { ...; } | { ...; }; }[]; pageHeading: Branded<...>; }' but required in type 'ViewModel'.

37   } satisfies ViewModel)),
       ~~~~~~~~~

  src/html-pages/save-article-form-page/view-model.ts:15:3
    15   newPropertyWeWantToAdd: string,
         ~~~~~~~~~~~~~~~~~~~~~~
    'newPropertyWeWantToAdd' is declared here.

[09:35:51] Found 2 errors. Watching for file changes.
```