Allow compiler to include browser-related APIs even if the application runs on Node.js
Two libraries depend on these types:
```
node_modules/axios-cache-interceptor/dist/storage/web-api.d.ts:26:50 - error TS2304: Cannot find name 'Storage'.

26 export declare function buildWebStorage(storage: Storage, prefix?: string): import("./types.js").AxiosStorage;
                                                    ~~~~~~~

node_modules/taiko/types/taiko/index.d.ts:676:44 - error TS2304: Cannot find name 'HTMLElement'.

676 export type EvaluateHandler<T> = (element: HTMLElement, args?: EvaluateHandlerArgs) => T;
```

In the case of `axios-cache-interceptor`, we don't use the offending
code.

In the case of Taiko, the dependency is only on the type rather than any
implementation, so the code once compiled should run correctly in Node.

A side-effect of this is that `window`, `document` and possibly other
global variables become visible everywhere (even if they don't exist in
Node).