Upgrade jest and related tools to v28
jest-environment-jsdom has been split out into it own package, and
needs to be installed separately now.
It is only needed by `fetch-dataset.test.ts` which is also thing
that fails after the upgrade.

It appears that some interaction between the environments and
ts-jest is affected.

I do not understand why we use jsdom for (only) this test.

```
Summary of all failing tests
 FAIL  test/infrastructure/fetch-dataset.test.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its
dependencies use non-standard JavaScript syntax, or when Jest is not
configured to support
such syntax.

    Out of the box Jest supports Babel, which will be used to transform
your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see
https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see
https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can
specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option
in your config.
     • If you simply want to mock your non-JS modules (e.g. binary
assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the
docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    SyntaxError: Unexpected token 'export'

      at Runtime.createScriptFromCode
(node_modules/jest-runtime/build/index.js:1773:14)
      at Object.<anonymous>
(node_modules/cls-rtracer/src/rtracer.js:4:24)
```