Reduce to one compilation error
```
src/html-pages/save-article-form-page/construct-view-model.ts:30:34 - error TS2741: Property 'newPropertyWeWantToAdd' is missing in type '{ article: { name: SanitisedHtmlFragment; id: ArticleId; }; userLists: readonly { id: ListId; name: string; description: string; articleIds: string[]; updatedAt: Date; ownerId: { ...; } | { ...; }; }[]; pageHeading: Branded<...>; }' but required in type 'ViewModel'.

 30   TE.map((partial): ViewModel => ({
                                     ~~
 31     article: {
    ~~~~~~~~~~~~~~
...
 36     pageHeading: toHtmlFragment('Save article'),
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 37   })),
    ~~~~

  src/html-pages/save-article-form-page/view-model.ts:15:3
    15   newPropertyWeWantToAdd: string,
         ~~~~~~~~~~~~~~~~~~~~~~
    'newPropertyWeWantToAdd' is declared here.

[09:37:27] Found 1 error. Watching for file changes.
```